
package garcia_recu;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "recu_garcia_web_operaciones_9a", targetNamespace = "http://garcia_recu/", wsdlLocation = "http://localhost:8080/recu_garcia_9a/recu_garcia_web_operaciones_9a?wsdl")
public class RecuGarciaWebOperaciones9A_Service
    extends Service
{

    private static final URL RECUGARCIAWEBOPERACIONES9A_WSDL_LOCATION;
    private static final WebServiceException RECUGARCIAWEBOPERACIONES9A_EXCEPTION;
    private static final QName RECUGARCIAWEBOPERACIONES9A_QNAME = new QName("http://garcia_recu/", "recu_garcia_web_operaciones_9a");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/recu_garcia_9a/recu_garcia_web_operaciones_9a?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECUGARCIAWEBOPERACIONES9A_WSDL_LOCATION = url;
        RECUGARCIAWEBOPERACIONES9A_EXCEPTION = e;
    }

    public RecuGarciaWebOperaciones9A_Service() {
        super(__getWsdlLocation(), RECUGARCIAWEBOPERACIONES9A_QNAME);
    }

    public RecuGarciaWebOperaciones9A_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECUGARCIAWEBOPERACIONES9A_QNAME, features);
    }

    public RecuGarciaWebOperaciones9A_Service(URL wsdlLocation) {
        super(wsdlLocation, RECUGARCIAWEBOPERACIONES9A_QNAME);
    }

    public RecuGarciaWebOperaciones9A_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECUGARCIAWEBOPERACIONES9A_QNAME, features);
    }

    public RecuGarciaWebOperaciones9A_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecuGarciaWebOperaciones9A_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecuGarciaWebOperaciones9A
     */
    @WebEndpoint(name = "recu_garcia_web_operaciones_9aPort")
    public RecuGarciaWebOperaciones9A getRecuGarciaWebOperaciones9APort() {
        return super.getPort(new QName("http://garcia_recu/", "recu_garcia_web_operaciones_9aPort"), RecuGarciaWebOperaciones9A.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecuGarciaWebOperaciones9A
     */
    @WebEndpoint(name = "recu_garcia_web_operaciones_9aPort")
    public RecuGarciaWebOperaciones9A getRecuGarciaWebOperaciones9APort(WebServiceFeature... features) {
        return super.getPort(new QName("http://garcia_recu/", "recu_garcia_web_operaciones_9aPort"), RecuGarciaWebOperaciones9A.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECUGARCIAWEBOPERACIONES9A_EXCEPTION!= null) {
            throw RECUGARCIAWEBOPERACIONES9A_EXCEPTION;
        }
        return RECUGARCIAWEBOPERACIONES9A_WSDL_LOCATION;
    }

}
