
package garcia_recu;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "recu_garcia_web_operaciones_9a", targetNamespace = "http://garcia_recu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecuGarciaWebOperaciones9A {


    /**
     * 
     * @param densidad
     * @param volumen
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularMasa", targetNamespace = "http://garcia_recu/", className = "garcia_recu.CalcularMasa")
    @ResponseWrapper(localName = "calcularMasaResponse", targetNamespace = "http://garcia_recu/", className = "garcia_recu.CalcularMasaResponse")
    @Action(input = "http://garcia_recu/recu_garcia_web_operaciones_9a/calcularMasaRequest", output = "http://garcia_recu/recu_garcia_web_operaciones_9a/calcularMasaResponse")
    public double calcularMasa(
        @WebParam(name = "densidad", targetNamespace = "")
        double densidad,
        @WebParam(name = "volumen", targetNamespace = "")
        double volumen);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://garcia_recu/", className = "garcia_recu.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://garcia_recu/", className = "garcia_recu.HelloResponse")
    @Action(input = "http://garcia_recu/recu_garcia_web_operaciones_9a/helloRequest", output = "http://garcia_recu/recu_garcia_web_operaciones_9a/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
